spring:
  application:
    name: statemachine-sample
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    platform: h2
    url: "jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false"
    username: sa
    password:
  jpa:
    generate-ddl: true
    hibernate:
      use-new-id-generator-mappings: true

logging:
  level:
    root: 'INFO'
    org.hibernate.SQL: DEBUG
